[package]
name = "scuffscript"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.96", features = ["backtrace"] }
clap = { version = "4.5.7", features = ["derive"] }
thiserror = "2.0.11"
which = "6.0.1"
